version: "3.8"

services:
  poker_api:
    image: poker_api:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: development
    volumes:
      - .:/app
    env_file:
      - .env.local
    ports:
      - "3001:3001"
      - "403:403"
    depends_on:
      - poker_postgres
      - poker_redis
    stdin_open: true
    tty: true

  poker_background_jobs:
    image: poker_api:latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RAILS_ENV: development
    command: ["bundle", "exec", "sidekiq"]
    volumes:
      - .:/app
    env_file:
      - .env.local
    depends_on:
      - poker_redis
      - poker_postgres
    stdin_open: true
    tty: true

  poker_redis:
    image: redis:6.0.8
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/data/redis:/var/lib/redis
      - ./tmp/data/redis.conf:/usr/local/etc/redis/redis.conf

  poker_postgres:
    image: postgres:12.4
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: poker_backend
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/data/postgres:/var/lib/postgresql/data
    stdin_open: true
    tty: true
